import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

/**
 * Sidebar for the licence content track (Feature 015, ADR-0020).
 *
 * Autogenerated from the folder structure, the same way the curriculum sidebar
 * is, so adding a licence course stays a content-only change (Constitution Art.
 * V.4). This track deliberately does NOT appear in the semester sidebar:
 * EED-313 is not part of the approved 2026 scheme, and showing it there would
 * imply it is (research R3).
 */
const sidebars: SidebarsConfig = {
  licenceSidebar: [{ type: 'autogenerated', dirName: '.' }],
};

export default sidebars;
