import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

/**
 * Sidebar for the `guides` docs-plugin instance (Spec 004, ADR-0009, T001).
 * Autogenerated from `guides/` — same "folder structure is the source of
 * truth" convention as the curriculum's own sidebars.ts, kept as a separate
 * file/instance so this topic-based navigation never mixes with the
 * curriculum's semester -> course -> unit sidebar.
 */
const sidebars: SidebarsConfig = {
  guides: [{ type: 'autogenerated', dirName: '.' }],
};

export default sidebars;
