import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

/**
 * Fully autogenerated Semester -> Course -> Unit sidebar (FR-004, FR-005).
 * Structure comes entirely from the docs/ folders + _category_.json files, so
 * adding a course requires no change here (SC-006).
 */
const sidebars: SidebarsConfig = {
  textbook: [{ type: 'autogenerated', dirName: '.' }],
};

export default sidebars;
