import { chromium } from 'playwright';
const browser = await chromium.launch();
const ctx = await browser.newContext({ viewport: { width: 1280, height: 800 } });
const page = await ctx.newPage();
const bad = [];
page.on('response', (r) => { if (r.status() >= 400) bad.push(`${r.status()} ${r.url()}`); });
page.on('console', (m) => { if (m.type() === 'error') bad.push(`console: ${m.text().slice(0, 120)}`); });
await page.goto('http://localhost:3457/semester-1/gnas-301/', { waitUntil: 'networkidle' });
await page.waitForTimeout(500);
console.log(JSON.stringify(bad, null, 1));
await browser.close();
